### ISSUE TITLE
Vérifier son html dans un validateur 

### ISSUE THREAD

**Issue by hugoblanc** [Choups/station_velo_services#1]
Le validateur indique les erreurs basiques: 
```html
                        <img
                                src="img/juju1.jpg"
                                alt="Julie"
                                width="300px"
                                height="300px"
                            />
```

au lieu de 

```html
                        <img
                                src="img/juju1.jpg"
                                alt="Julie"
                                width="300"
                                height="300"
                            />
```

Aussi c'est une mauvaise pratique que d'oublier l'attribut alt d'une balise img.

Pas mal d'erreur de ce genre, je vous laisse passer votre code dans le validateur pour plus de détaills 

> Bad value name for attribute type on element input.
```html
 <input type="name" name="name" placeholder="Nom, prenom" />
```

> Attribute placeholder is only allowed when the input type is email, number, password, search, tel, text, or url.

> Je ne connais aucun type name 
```html
<input type="name" name="name" placeholder="Nom, prenom" />
```

> Erreur ID null 
```html
<select name="Raison" id="">
```

> The frameborder attribute on the iframe element is obsolete.

>The marginheight attribute on the iframe element is obsolete

>The marginwidth attribute on the iframe element is obsolete.

Bref pas mal de petite erreurs: je vous conseille de vérifier et de corriger quand vous avez le temps ;) 

https://validator.w3.org/#validate_by_input

**Comment by alexandre-peyrichout** [comment]
fixed, thank you.
